import type { Metadata } from "next";
import "@/styles/globals.css";

import { Rubik, Questrial } from "next/font/google";
import { ReduxProvider } from "@/store/provider";
import { Footer, Navbar } from "@/components";
import { AppInitializer } from "@/components/AppInitializer";
import AuthForms from "@/components/AuthForm";

export const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rubik",
});

export const questrial = Questrial({
  subsets: ["latin"],
  weight: "400",
  display: "swap",
  variable: "--font-questrial",
});

export const metadata: Metadata = {
  title: "Fresh Harvests",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth" lang="en">
      <body
        className={`min-h-screen flex flex-col ${rubik.variable} ${questrial.variable} antialiased`}
      >
        <ReduxProvider>
          <AppInitializer />
          <Navbar />
          <main className="flex-1">{children}</main>
          <Footer />
          <AuthForms />
        </ReduxProvider>
      </body>
    </html>
  );
}
